# Generated by Django 4.2 on 2023-05-04 11:30

import car.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='cus', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default='123 Street', max_length=100)),
                ('email', models.EmailField(default='test@gmail.com', max_length=100)),
                ('city', models.CharField(default='City', max_length=100)),
                ('district', models.CharField(default='district', max_length=100)),
                ('ward', models.CharField(default='district', max_length=100)),
                ('contact', models.CharField(default='0123456789', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='prd', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=car.models.product_directory_path)),
                ('category', models.CharField(choices=[('car interior', 'Car Interior'), ('car exterior', 'Car Exterior'), ('car accessories', 'Car Accessories'), ('car care services', 'Car Care Services'), ('car parts', 'Car Parts')], default='car interior', max_length=100)),
                ('description', models.TextField(blank=True, default='This is the product', null=True)),
                ('cost_price', models.DecimalField(decimal_places=2, default='1.99', max_digits=65)),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=65)),
                ('old_price', models.DecimalField(decimal_places=2, default='1.99', max_digits=65)),
                ('stock_count', models.CharField(blank=True, default='8', max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='sup', unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='test@gmail.com', max_length=100)),
                ('image', models.ImageField(default='supplier.png', upload_to='supplier-images')),
                ('address', models.CharField(default='111 Tran Phu', max_length=100)),
                ('contact', models.CharField(default='0123456789', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Supplier',
            },
        ),
        migrations.CreateModel(
            name='StatisticsProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default='1.99', max_digits=65)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='car.products')),
            ],
            options={
                'verbose_name_plural': 'StatisticsProduct',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='rep', unique=True)),
                ('report_text', models.TextField(blank=True, default='This is a report', null=True)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.CharField(choices=[('inventory report', 'Inventory report'), ('sales report', 'Sales report')], default='inventory report', max_length=100)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Report',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='car.supplier'),
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='product.png', upload_to='product-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_images', to='car.products')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='ord', unique=True)),
                ('grand_total', models.DecimalField(decimal_places=2, default='1.99', max_digits=65)),
                ('tax', models.DecimalField(decimal_places=2, default='1.99', max_digits=65)),
                ('total_price', models.DecimalField(decimal_places=2, default='1.99', max_digits=65)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='inv', unique=True)),
                ('prod', jsonfield.fields.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='coi', unique=True)),
                ('grand_total', models.DecimalField(decimal_places=2, default='1.99', max_digits=65)),
                ('tax', models.DecimalField(decimal_places=2, default='1.99', max_digits=65)),
                ('total_price', models.DecimalField(decimal_places=2, default='1.99', max_digits=65)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_order_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CartOrderItems',
            },
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='car', unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=65)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_orders', to='car.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CartOrder',
            },
        ),
    ]
